version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq-local'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_net

#  postgres:
#    build:
#      context: ./../auth-app
#      dockerfile: Dockerfile
#    restart: always
#    deploy:
#      mode: replicated
#      replicas: 1
#    volumes:
#      - ./../auth-app/data:/app/auth-app/data
#    ports:
#      - "5000:5000"


networks:
  rabbitmq_net:
    driver: bridge