apiVersion: apps/v1
kind: Deployment
metadata:
  name: ramein-orion
spec:
  selector:
    matchLabels:
      app: ramein-orion
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: ramein-orion
    spec:
      containers:
        - name: ramein-orion
          image: andibalo213/ramein-orion:0.1
          env:
            - name: APP_ENV
              value: "DEV"
            - name: APP_VERSION
              value: "0.1"
            - name: APP_ID
              value: "ORION"
            - name: DB_DSN
              value: "postgres://postgres:postgres@ramein-orion-postgres-service:5432/orion_db?sslmode=disable"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              value: "postgres"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "orion_db"
            - name: RABBITMQ_URL
              value: "amqp://guest:guest@stg-rabbitmqcluster.rabbitmq.svc.cluster.local:5672"
            - name: RABBITMQ_CHANNEL
              value: "orion-stg"
            - name: SENDINBLUE_API_KEY
              value: "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"
          imagePullPolicy: Always
          ports:
            - containerPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: ramein-orion-service
spec:
  selector:
    app: ramein-orion
  ports:
    - port: 8001
      targetPort: 8001
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ramein-core
spec:
  selector:
    matchLabels:
      app: ramein-core
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: ramein-core
    spec:
      containers:
        - name: ramein-core
          image: andibalo213/ramein-core:0.1
          env:
            - name: APP_ENV
              value: "DEV"
            - name: APP_VERSION
              value: "0.1"
            - name: APP_ID
              value: "CORE"
            - name: DB_DSN
              value: "postgres://postgres:postgres@ramein-core-postgres-service:5432/core_db?sslmode=disable"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              value: "postgres"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "core_db"
            - name: RABBITMQ_URL
              value: "amqp://guest:guest@stg-rabbitmqcluster.rabbitmq.svc.cluster.local:5672"
            - name: RABBITMQ_CHANNEL
              value: "core-stg"
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: ramein-core-service
spec:
  selector:
    app: ramein-core
  ports:
    - port: 8000
      targetPort: 8000
  type: LoadBalancer
