apiVersion: apps/v1
kind: Deployment
metadata:
  name: ramein-core-postgres
spec:
  selector:
    matchLabels:
      app: ramein-core-postgres
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: ramein-core-postgres
    spec:
      containers:
        - name: ramein-core-postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          envFrom:
            # Load the environment variables/PostgresSQL credentials
            - configMapRef:
                # This should be the ConfigMap name created ealier
                name: ramein-core-postgres-credentials
          volumeMounts:
            - name: postgres-persistent-storage
              mountPath: /var/lib/postgres/data
      volumes:
        - name: postgres-persistent-storage
          # pointer to the configuration of HOW we want the mount to be implemented
          persistentVolumeClaim:
            claimName: local-storage
---
kind: Service
apiVersion: v1
metadata:
  name: ramein-core-postgres-service
spec:
  ports:
    - port: 5432
  type: ClusterIP
  selector:
    app: postgres

---
# What do want?
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  storageClassName: cloud-ssd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 7Gi
---
# How do we want it implemented
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cloud-ssd
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
---
# LOCAL
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-storage
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 7Gi
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-local-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: "/data/local"
    type: DirectoryOrCreate
