// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"fms/internal/biz"
	"fms/internal/conf"
	"fms/internal/data"
	"fms/internal/server"
	"fms/internal/service"
	"fms/third_party/google"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}

	gcsClient := google.NewGoogleCloudStorageClient(log.NewHelper(logger))
	greeterRepo := data.NewGreeterRepo(dataData, logger)
	greeterUsecase := biz.NewGreeterUsecase(greeterRepo, logger)
	greeterService := service.NewGreeterService(greeterUsecase)
	gcsRepo := data.NewGoogleCloudStorageRepo(gcsClient, logger)
	fileUsecase := biz.NewFileUsecase(logger, gcsRepo)
	fileService := service.NewFileService(fileUsecase)
	grpcServer := server.NewGRPCServer(confServer, greeterService, fileService, logger)
	httpServer := server.NewHTTPServer(confServer, greeterService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
